# Generated by Django 3.0.7 on 2020-07-23 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200720_1307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='provider_info_profile',
            new_name='provider_info',
        ),
        migrations.RenameField(
            model_name='profileimage',
            old_name='provider_info_image',
            new_name='provider_info',
        ),
        migrations.RenameField(
            model_name='providerinfopayment',
            old_name='provider_info_payment',
            new_name='provider_info',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='provider_info_review',
            new_name='provider_info',
        ),
        migrations.RenameField(
            model_name='subimages',
            old_name='provider_info_subimage',
            new_name='provider_info',
        ),
    ]
