# Generated by Django 3.0.7 on 2020-07-14 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200713_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerinfo',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
